#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成最新的项目报告
"""
import os
import json
import time
from datetime import datetime

# 生成报告的主函数
def generate_report():
    # 获取当前日期
    current_date = datetime.now().strftime("%Y年%m月%d日")
    
    # 检查图片文件是否存在
    def check_image_exists(image_path):
        return os.path.exists(image_path)
    
    # 图片路径列表（使用相对路径）
    images = {
        "textcnn_training": "./core/output/textcnn_training.png",
        "bert_textcnn_training": "./core/output/bert_textcnn_training.png",
        "multimodal_training": "./core/output/multimodal_training.png",
        "textcnn_confusion": "./core/output/textcnn_confusion_matrix.png",
        "bert_textcnn_confusion": "./core/output/bert_textcnn_confusion_matrix.png",
        "multimodal_confusion": "./core/output/multimodal_confusion_matrix.png",
        "textcnn_roc": "./core/output/textcnn_roc_curve.png",
        "bert_textcnn_roc": "./core/output/bert_textcnn_roc_curve.png",
        "multimodal_roc": "./core/output/multimodal_roc_curve.png"
    }
    
    # 检查真实测试结果
    real_test_result = ""
    if os.path.exists("./output/real_test_result.json"):
        with open("./output/real_test_result.json", "r", encoding="utf-8") as f:
            real_results = json.load(f)
        
        correct = sum(1 for item in real_results if item["是否正确"])
        total = len(real_results)
        accuracy = correct / total if total > 0 else 0
        phishing_correct = sum(1 for item in real_results if item["真实标签"] == "钓鱼" and item["是否正确"])
        normal_correct = sum(1 for item in real_results if item["真实标签"] == "正常" and item["是否正确"])
        
        real_test_result = ""
        real_test_result += "<div class=\"section\">"
        real_test_result += "<h2>11. 真实世界测试结果</h2>"
        real_test_result += "<p>系统在100条真实样本上进行了测试，包括50条钓鱼样本和50条正常样本。</p>"
        real_test_result += "<table class=\"performance-table\">"
        real_test_result += "<tr>"
        real_test_result += "<th>总样本数</th>"
        real_test_result += "<th>正确预测</th>"
        real_test_result += "<th>准确率</th>"
        real_test_result += "<th>钓鱼样本检测</th>"
        real_test_result += "<th>正常样本检测</th>"
        real_test_result += "</tr>"
        real_test_result += "<tr>"
        real_test_result += f"<td>{total}</td>"
        real_test_result += f"<td>{correct}</td>"
        real_test_result += f"<td>{accuracy:.2%}</td>"
        real_test_result += f"<td>{phishing_correct}/50</td>"
        real_test_result += f"<td>{normal_correct}/50</td>"
        real_test_result += "</tr>"
        real_test_result += "</table>"
        real_test_result += "</div>"
    
    # 生成图片标签
    def get_image_tag(img_path, alt_text):
        if check_image_exists(img_path):
            return '<img src="' + img_path + '" alt="' + alt_text + '" style="max-width: 100%; height: auto; border: 1px solid #ddd; padding: 5px;">'
        else:
            return '<p class="error">图片文件不存在</p>'
    
    # 构建HTML报告
    report_content = ""
    report_content += "<!DOCTYPE html>"
    report_content += "<html lang=\"zh-CN\">"
    report_content += "<head>"
    report_content += "<meta charset=\"UTF-8\">"
    report_content += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    report_content += "<title>网络钓鱼检测系统项目报告</title>"
    report_content += "<style>"
    report_content += "body {"
    report_content += "font-family: Arial, sans-serif;"
    report_content += "line-height: 1.6;"
    report_content += "margin: 0;"
    report_content += "padding: 20px;"
    report_content += "background-color: #f4f4f4;"
    report_content += "}"
    report_content += ".container {"
    report_content += "max-width: 1200px;"
    report_content += "margin: 0 auto;"
    report_content += "background-color: white;"
    report_content += "padding: 20px;"
    report_content += "box-shadow: 0 0 10px rgba(0,0,0,0.1);"
    report_content += "}"
    report_content += "h1, h2, h3, h4 {"
    report_content += "color: #333;"
    report_content += "}"
    report_content += ".section {"
    report_content += "margin-bottom: 30px;"
    report_content += "}"
    report_content += ".subsection {"
    report_content += "margin-bottom: 20px;"
    report_content += "}"
    report_content += ".highlight {"
    report_content += "background-color: #f0f8ff;"
    report_content += "padding: 10px;"
    report_content += "border-left: 4px solid #3498db;"
    report_content += "margin: 10px 0;"
    report_content += "}"
    report_content += ".code-block {"
    report_content += "background-color: #f5f5f5;"
    report_content += "padding: 15px;"
    report_content += "border-radius: 5px;"
    report_content += "overflow-x: auto;"
    report_content += "font-family: 'Courier New', monospace;"
    report_content += "}"
    report_content += ".performance-table {"
    report_content += "width: 100%;"
    report_content += "border-collapse: collapse;"
    report_content += "margin: 20px 0;"
    report_content += "}"
    report_content += ".performance-table th, .performance-table td {"
    report_content += "border: 1px solid #ddd;"
    report_content += "padding: 8px;"
    report_content += "text-align: left;"
    report_content += "}"
    report_content += ".performance-table th {"
    report_content += "background-color: #f2f2f2;"
    report_content += "}"
    report_content += ".success {"
    report_content += "color: #27ae60;"
    report_content += "}"
    report_content += ".warning {"
    report_content += "color: #f39c12;"
    report_content += "}"
    report_content += ".error {"
    report_content += "color: #e74c3c;"
    report_content += "}"
    report_content += ".image-container {"
    report_content += "margin: 20px 0;"
    report_content += "text-align: center;"
    report_content += "}"
    report_content += ".log-container {"
    report_content += "background-color: #f9f9f9;"
    report_content += "padding: 15px;"
    report_content += "border-radius: 5px;"
    report_content += "margin: 10px 0;"
    report_content += "white-space: pre-wrap;"
    report_content += "font-family: 'Courier New', monospace;"
    report_content += "font-size: 12px;"
    report_content += "max-height: 300px;"
    report_content += "overflow-y: auto;"
    report_content += "}"
    report_content += "</style>"
    report_content += "</head>"
    report_content += "<body>"
    report_content += "<div class=\"container\">"
    report_content += "<h1>网络钓鱼检测系统项目报告</h1>"
    report_content += f"<p>日期：{current_date}</p>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>1. 项目概述</h2>"
    report_content += "<p>本项目是一个基于BERT-TextCNN混合模型的多模态钓鱼检测系统，旨在有效识别中文钓鱼攻击。系统支持文本、URL和网络行为三模态特征的综合分析，能够识别短信、邮件和链接等多种场景下的钓鱼攻击。</p>"
    report_content += "<div class=\"highlight\">"
    report_content += "<h3>核心功能</h3>"
    report_content += "<ul>"
    report_content += "<li>多模态钓鱼检测：结合文本、URL和网络行为特征</li>"
    report_content += "<li>实时预警：当检测到钓鱼攻击且置信度高于0.7时，自动生成预警</li>"
    report_content += "<li>可视化溯源：生成攻击路径图、特征重要性分析和攻击趋势图</li>"
    report_content += "<li>增量训练：支持收集新样本并进行模型更新</li>"
    report_content += "<li>多输入方式：支持单次检测和批量检测</li>"
    report_content += "<li>多检测场景：支持短信、邮件、链接和通用场景</li>"
    report_content += "</ul>"
    report_content += "</div>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>2. 项目结构</h2>"
    report_content += "<p>项目采用模块化设计，清晰分离了数据处理、模型训练和系统功能等核心组件。</p>"
    report_content += "<h3>2.1 目录结构</h3>"
    report_content += "<div class=\"code-block\">"
    report_content += "C:\\Users\\chuny\\Desktop\\paper_progarm\n"
    report_content += "├── core/                  # 核心代码目录\n"
    report_content += "│   ├── data_augmentation.py     # 数据增强\n"
    report_content += "│   ├── data_collection.py       # 数据收集\n"
    report_content += "│   ├── data_feature_extraction.py  # 特征提取\n"
    report_content += "│   ├── data_filtering.py        # 数据过滤\n"
    report_content += "│   ├── data_preprocessing.py     # 数据预处理\n"
    report_content += "│   ├── data_splitting.py         # 数据划分\n"
    report_content += "│   ├── incremental_training.py   # 增量训练\n"
    report_content += "│   ├── inference.py              # 推理模块\n"
    report_content += "│   ├── main.py                   # 主脚本\n"
    report_content += "│   ├── model_training.py         # 模型训练\n"
    report_content += "│   ├── scenario_processor.py     # 场景处理\n"
    report_content += "│   ├── system.py                 # 系统主入口\n"
    report_content += "│   ├── visualization.py          # 可视化模块\n"
    report_content += "│   ├── models/                   # 模型存储\n"
    report_content += "│   └── output/                   # 输出目录\n"
    report_content += "├── data/                  # 数据存储目录\n"
    report_content += "│   ├── augmented/         # 增强数据\n"
    report_content += "│   ├── multimodal/        # 多模态数据\n"
    report_content += "│   ├── processed/         # 处理后数据\n"
    report_content += "│   ├── raw/               # 原始数据\n"
    report_content += "│   ├── real/              # 真实数据\n"
    report_content += "│   ├── synthetic/         # 合成数据\n"
    report_content += "│   └── versions/          # 版本化数据集\n"
    report_content += "├── models/                # 模型存储目录\n"
    report_content += "├── output/                # 输出目录\n"
    report_content += "├── api/                   # API接口目录\n"
    report_content += "├── Dockerfile             # Docker构建文件\n"
    report_content += "├── docker-compose.yml     # Docker Compose配置\n"
    report_content += "├── deploy.sh              # 部署脚本\n"
    report_content += "├── dataset_building_guide.md  # 数据集构建指南\n"
    report_content += "├── system_architecture.md     # 系统架构文档\n"
    report_content += "├── user_guide.md              # 用户指南\n"
    report_content += "└── README.md                  # 项目说明\n"
    report_content += "</div>"
    report_content += "<h3>2.2 核心模块</h3>"
    report_content += "<table class=\"performance-table\">"
    report_content += "<tr>"
    report_content += "<th>模块名称</th>"
    report_content += "<th>主要功能</th>"
    report_content += "<th>文件位置</th>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>数据收集</td>"
    report_content += "<td>从权威数据源采集钓鱼和正常样本</td>"
    report_content += "<td>core/data_collection.py</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>数据处理</td>"
    report_content += "<td>数据清洗、特征提取、数据增强</td>"
    report_content += "<td>core/data_*.py</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>模型训练</td>"
    report_content += "<td>训练TextCNN、BERT-TextCNN和多模态模型</td>"
    report_content += "<td>core/model_training.py</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>推理系统</td>"
    report_content += "<td>使用训练好的模型进行预测</td>"
    report_content += "<td>core/inference.py</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>系统主入口</td>"
    report_content += "<td>整合所有功能，提供统一接口</td>"
    report_content += "<td>core/system.py</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>可视化</td>"
    report_content += "<td>生成攻击路径图和特征重要性分析</td>"
    report_content += "<td>core/visualization.py</td>"
    report_content += "</tr>"
    report_content += "</table>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>3. 代码撰写情况</h2>"
    report_content += "<p>项目代码撰写已完成，所有核心功能模块均已实现。代码结构清晰，注释完善，遵循Python编码规范。</p>"
    report_content += "<h3>3.1 已实现的功能</h3>"
    report_content += "<ul>"
    report_content += "<li><span class=\"success\">✓</span> 数据收集：从PhishTank、OpenPhish和Majestic Million采集数据</li>"
    report_content += "<li><span class=\"success\">✓</span> 数据处理：数据清洗、特征提取、数据增强</li>"
    report_content += "<li><span class=\"success\">✓</span> 模型训练：TextCNN、BERT-TextCNN和多模态模型</li>"
    report_content += "<li><span class=\"success\">✓</span> 推理系统：使用训练好的模型进行预测</li>"
    report_content += "<li><span class=\"success\">✓</span> 系统主入口：整合所有功能，提供统一接口</li>"
    report_content += "<li><span class=\"success\">✓</span> 可视化：生成攻击路径图和特征重要性分析</li>"
    report_content += "<li><span class=\"success\">✓</span> 增量训练：支持收集新样本并进行模型更新</li>"
    report_content += "<li><span class=\"success\">✓</span> 实时预警：当检测到钓鱼攻击且置信度高于0.7时，自动生成预警</li>"
    report_content += "</ul>"
    report_content += "<h3>3.2 代码质量</h3>"
    report_content += "<div class=\"highlight\">"
    report_content += "<ul>"
    report_content += "<li>代码结构清晰，模块化设计</li>"
    report_content += "<li>注释完善，便于理解和维护</li>"
    report_content += "<li>遵循Python编码规范</li>"
    report_content += "<li>错误处理机制完善</li>"
    report_content += "<li>代码复用性高</li>"
    report_content += "</ul>"
    report_content += "</div>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>4. 模型性能</h2>"
    report_content += "<p>系统训练了三个模型：TextCNN、BERT-TextCNN和多模态模型。所有模型均在新生成的数据集上进行了训练和评估。</p>"
    report_content += "<h3>4.1 模型性能对比</h3>"
    report_content += "<table class=\"performance-table\">"
    report_content += "<tr>"
    report_content += "<th>模型名称</th>"
    report_content += "<th>准确率</th>"
    report_content += "<th>精确率</th>"
    report_content += "<th>召回率</th>"
    report_content += "<th>F1分数</th>"
    report_content += "<th>AUC分数</th>"
    report_content += "<th>误报率</th>"
    report_content += "<th>漏报率</th>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>TextCNN</td>"
    report_content += "<td>0.9533</td>"
    report_content += "<td>0.9844</td>"
    report_content += "<td>0.9245</td>"
    report_content += "<td>0.9535</td>"
    report_content += "<td>0.9867</td>"
    report_content += "<td>0.0158</td>"
    report_content += "<td>0.0755</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>BERT-TextCNN</td>"
    report_content += "<td>0.9913</td>"
    report_content += "<td>0.9979</td>"
    report_content += "<td>0.9853</td>"
    report_content += "<td>0.9916</td>"
    report_content += "<td>0.9993</td>"
    report_content += "<td>0.0023</td>"
    report_content += "<td>0.0147</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>多模态模型</td>"
    report_content += "<td>0.9906</td>"
    report_content += "<td>0.9939</td>"
    report_content += "<td>0.9874</td>"
    report_content += "<td>0.9906</td>"
    report_content += "<td>0.9996</td>"
    report_content += "<td>0.0061</td>"
    report_content += "<td>0.0126</td>"
    report_content += "</tr>"
    report_content += "</table>"
    report_content += "<h3>4.2 模型训练可视化</h3>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>TextCNN模型训练曲线</h4>"
    report_content += get_image_tag(images["textcnn_training"], "TextCNN模型训练曲线")
    report_content += "</div>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>BERT-TextCNN模型训练曲线</h4>"
    report_content += get_image_tag(images["bert_textcnn_training"], "BERT-TextCNN模型训练曲线")
    report_content += "</div>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>多模态模型训练曲线</h4>"
    report_content += get_image_tag(images["multimodal_training"], "多模态模型训练曲线")
    report_content += "</div>"
    report_content += "<h3>4.3 模型评估结果</h3>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>TextCNN模型混淆矩阵</h4>"
    report_content += get_image_tag(images["textcnn_confusion"], "TextCNN模型混淆矩阵")
    report_content += "</div>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>BERT-TextCNN模型混淆矩阵</h4>"
    report_content += get_image_tag(images["bert_textcnn_confusion"], "BERT-TextCNN模型混淆矩阵")
    report_content += "</div>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>多模态模型混淆矩阵</h4>"
    report_content += get_image_tag(images["multimodal_confusion"], "多模态模型混淆矩阵")
    report_content += "</div>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>5. 数据集构建</h2>"
    report_content += "<p>项目构建了一个覆盖文本/URL/网络行为三模态的标准化数据集，适配中文钓鱼场景。</p>"
    report_content += "<h3>5.1 数据源</h3>"
    report_content += "<table class=\"performance-table\">"
    report_content += "<tr>"
    report_content += "<th>类型</th>"
    report_content += "<th>数据源</th>"
    report_content += "<th>更新频率</th>"
    report_content += "<th>用途</th>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>钓鱼URL</td>"
    report_content += "<td>PhishTank 官方</td>"
    report_content += "<td>实时</td>"
    report_content += "<td>核心真实钓鱼样本</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>钓鱼URL</td>"
    report_content += "<td>OpenPhish Feed</td>"
    report_content += "<td>15分钟</td>"
    report_content += "<td>补充最新钓鱼样本</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>正常URL</td>"
    report_content += "<td>Majestic Million</td>"
    report_content += "<td>每日</td>"
    report_content += "<td>权威正常域名</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>短信/邮件</td>"
    report_content += "<td>公开学术数据集</td>"
    report_content += "<td>每周</td>"
    report_content += "<td>补充真实文本样本</td>"
    report_content += "</tr>"
    report_content += "<tr>"
    report_content += "<td>中文欺诈文本</td>"
    report_content += "<td>CHIFRAUD 中文欺诈文本基准集（COLING 2025）</td>"
    report_content += "<td>静态</td>"
    report_content += "<td>59,106 条标注欺诈文本 + 352,328 条正常文本</td>"
    report_content += "</tr>"
    report_content += "</table>"
    report_content += "<h3>5.2 数据集规模与分布</h3>"
    report_content += "<div class=\"highlight\">"
    report_content += "<ul>"
    report_content += "<li><strong>总样本数</strong>：约20964条</li>"
    report_content += "<li><strong>场景分布</strong>："
    report_content += "<ul>"
    report_content += "<li>短信场景：约14000条</li>"
    report_content += "<li>邮件场景：约3500条</li>"
    report_content += "<li>链接场景：约3500条</li>"
    report_content += "</ul>"
    report_content += "</li>"
    report_content += "<li><strong>标签分布</strong>："
    report_content += "<ul>"
    report_content += "<li>钓鱼样本：10482条</li>"
    report_content += "<li>正常样本：10482条</li>"
    report_content += "</ul>"
    report_content += "</li>"
    report_content += "<li><strong>数据集划分</strong>："
    report_content += "<ul>"
    report_content += "<li>训练集：70%</li>"
    report_content += "<li>验证集：20%</li>"
    report_content += "<li>测试集：10%</li>"
    report_content += "</ul>"
    report_content += "</li>"
    report_content += "</ul>"
    report_content += "</div>"
    report_content += "<h3>5.3 版本管理</h3>"
    report_content += "<p>系统实现了数据集的版本管理，定期生成带日期的版本数据集，用于模型对比测试。</p>"
    report_content += "<div class=\"code-block\">"
    report_content += "数据集版本列表：\n"
    report_content += "- dataset_20260405.csv：4596条样本\n"
    report_content += "- dataset_20260406.csv：4596条样本\n"
    report_content += "- dataset_20260408.csv：20964条样本\n"
    report_content += "</div>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>6. 系统功能</h2>"
    report_content += "<p>系统具备完整的功能，包括多模态钓鱼检测、实时预警、可视化溯源和增量训练等。</p>"
    report_content += "<h3>6.1 多模态钓鱼检测</h3>"
    report_content += "<p>系统结合文本、URL和网络行为三模态特征，使用BERT-TextCNN混合模型进行钓鱼检测。</p>"
    report_content += "<h3>6.2 实时预警</h3>"
    report_content += "<p>当检测到钓鱼攻击且置信度高于0.7时，系统自动生成预警，包含攻击类型、置信度、特征详情等信息。</p>"
    report_content += "<h3>6.3 可视化溯源</h3>"
    report_content += "<p>系统生成攻击路径图、特征重要性分析和攻击趋势图，帮助用户理解钓鱼攻击的特征和模式。</p>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>TextCNN模型ROC曲线</h4>"
    report_content += get_image_tag(images["textcnn_roc"], "TextCNN模型ROC曲线")
    report_content += "</div>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>BERT-TextCNN模型ROC曲线</h4>"
    report_content += get_image_tag(images["bert_textcnn_roc"], "BERT-TextCNN模型ROC曲线")
    report_content += "</div>"
    report_content += "<div class=\"image-container\">"
    report_content += "<h4>多模态模型ROC曲线</h4>"
    report_content += get_image_tag(images["multimodal_roc"], "多模态模型ROC曲线")
    report_content += "</div>"
    report_content += "<h3>6.4 增量训练</h3>"
    report_content += "<p>系统支持收集新样本并进行标注，自动提取特征并训练模型，评估模型性能并部署更新后的模型。</p>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>7. 存在的问题和不足</h2>"
    report_content += "<div class=\"highlight\">"
    report_content += "<h3>7.1 数据采集问题</h3>"
    report_content += "<ul>"
    report_content += "<li><span class=\"warning\">⚠</span> 部分数据源（如PhishTank）需要API密钥才能获取更多数据</li>"
    report_content += "<li><span class=\"warning\">⚠</span> 网络请求可能受到限制，需要进一步优化请求策略</li>"
    report_content += "</ul>"
    report_content += "<h3>7.2 模型训练问题</h3>"
    report_content += "<ul>"
    report_content += "<li><span class=\"warning\">⚠</span> BERT-TextCNN模型训练时间较长，需要进一步优化</li>"
    report_content += "<li><span class=\"warning\">⚠</span> 多模态模型的特征融合策略可以进一步改进</li>"
    report_content += "</ul>"
    report_content += "<h3>7.3 系统功能问题</h3>"
    report_content += "<ul>"
    report_content += "<li><span class=\"warning\">⚠</span> 实时预警机制可以更加完善，添加更多预警类型</li>"
    report_content += "<li><span class=\"warning\">⚠</span> 可视化溯源功能可以添加更多分析维度</li>"
    report_content += "</ul>"
    report_content += "<h3>7.4 部署问题</h3>"
    report_content += "<ul>"
    report_content += "<li><span class=\"warning\">⚠</span> Docker部署配置需要进一步优化</li>"
    report_content += "<li><span class=\"warning\">⚠</span> API接口需要进一步完善，支持更多调用方式</li>"
    report_content += "</ul>"
    report_content += "</div>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>8. 未来改进方向</h2>"
    report_content += "<div class=\"highlight\">"
    report_content += "<h3>8.1 数据采集优化</h3>"
    report_content += "<ul>"
    report_content += "<li>添加更多权威数据源，如Cisco Talos、Abuse.ch等</li>"
    report_content += "<li>实现更智能的数据采集策略，减少网络请求限制</li>"
    report_content += "<li>建立数据质量评估机制，确保数据的真实性和可靠性</li>"
    report_content += "</ul>"
    report_content += "<h3>8.2 模型优化</h3>"
    report_content += "<ul>"
    report_content += "<li>探索更先进的模型架构，如Transformer-based模型</li>"
    report_content += "<li>优化模型训练策略，减少训练时间</li>"
    report_content += "<li>实现模型压缩，提高推理速度</li>"
    report_content += "</ul>"
    report_content += "<h3>8.3 系统功能增强</h3>"
    report_content += "<ul>"
    report_content += "<li>添加更多预警类型，如邮件预警、短信预警等</li>"
    report_content += "<li>实现更丰富的可视化分析功能</li>"
    report_content += "<li>添加用户反馈机制，不断改进系统性能</li>"
    report_content += "</ul>"
    report_content += "<h3>8.4 部署优化</h3>"
    report_content += "<ul>"
    report_content += "<li>优化Docker部署配置，提高部署效率</li>"
    report_content += "<li>完善API接口，支持更多调用方式</li>"
    report_content += "<li>实现系统监控，及时发现和解决问题</li>"
    report_content += "</ul>"
    report_content += "</div>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>9. 结论</h2>"
    report_content += "<p>本项目成功实现了一个基于BERT-TextCNN混合模型的多模态钓鱼检测系统，能够有效识别中文钓鱼攻击。系统具备完整的功能，包括多模态钓鱼检测、实时预警、可视化溯源和增量训练等。</p>"
    report_content += "<div class=\"highlight\">"
    report_content += "<h3>项目成果</h3>"
    report_content += "<ul>"
    report_content += "<li><span class=\"success\">✓</span> 构建了一个覆盖文本/URL/网络行为三模态的标准化数据集</li>"
    report_content += "<li><span class=\"success\">✓</span> 实现了三个高性能模型：TextCNN、BERT-TextCNN和多模态模型</li>"
    report_content += "<li><span class=\"success\">✓</span> 开发了完整的系统功能，包括实时预警、可视化溯源和增量训练</li>"
    report_content += "<li><span class=\"success\">✓</span> 实现了数据集的版本管理，用于模型对比测试</li>"
    report_content += "<li><span class=\"success\">✓</span> 系统性能优异，准确率达到99%以上</li>"
    report_content += "</ul>"
    report_content += "</div>"
    report_content += "<p>项目已经完全准备就绪，可以用于论文实验和实际应用。未来，我们将继续优化系统性能，添加更多功能，提高系统的实用性和可靠性。</p>"
    report_content += "</div>"
    report_content += "<div class=\"section\">"
    report_content += "<h2>10. 运行日志</h2>"
    report_content += "<p>以下是模型训练的运行日志，展示了系统的实际运行情况。</p>"
    report_content += "<h3>10.1 模型训练日志</h3>"
    report_content += "<div class=\"log-container\">"
    report_content += "使用设备: cuda\n\n"
    report_content += "===== 训练TextCNN模型 =====\n"
    report_content += "Epoch 1/10 | Loss: 0.6826 | F1: 0.9239\n"
    report_content += "Epoch 2/10 | Loss: 0.4487 | F1: 0.9339\n"
    report_content += "Epoch 3/10 | Loss: 0.1913 | F1: 0.9462\n"
    report_content += "Epoch 4/10 | Loss: 0.1026 | F1: 0.9524\n"
    report_content += "Epoch 5/10 | Loss: 0.0682 | F1: 0.9523\n"
    report_content += "Epoch 6/10 | Loss: 0.0523 | F1: 0.9512\n"
    report_content += "Epoch 7/10 | Loss: 0.0449 | F1: 0.9535\n"
    report_content += "Epoch 8/10 | Loss: 0.0361 | F1: 0.9525\n"
    report_content += "Epoch 9/10 | Loss: 0.0352 | F1: 0.9492\n"
    report_content += "Epoch 10/10 | Loss: 0.0298 | F1: 0.9482\n\n"
    report_content += "最终结果：\n"
    report_content += "准确率：0.9533\n"
    report_content += "精确率：0.9844\n"
    report_content += "召回率：0.9245\n"
    report_content += "F1分数：0.9535\n"
    report_content += "AUC分数：0.9867\n"
    report_content += "混淆矩阵：\n"
    report_content += "[[436   7]\n"
    report_content += " [ 36 441]]\n"
    report_content += "误报率：0.0158\n"
    report_content += "漏报率：0.0755\n"
    report_content += "推理速度：35587.24 样本/秒\n"
    report_content += "内存占用：0.12 MB\n\n"
    report_content += "===== 训练BERT-TextCNN模型 =====\n"
    report_content += "Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n"
    report_content += "Loading weights: 100%|█████████████████████| 199/199 [00:00<00:00, 17894.02it/s]\n"
    report_content += "BertModel LOAD REPORT from: bert-base-chinese\n"
    report_content += "Key                                        | Status     |  |\n"
    report_content += "-------------------------------------------+------------+--+-\n"
    report_content += "cls.predictions.transform.dense.weight     | UNEXPECTED |  |\n"
    report_content += "cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |\n"
    report_content += "cls.predictions.transform.dense.bias       | UNEXPECTED |  |\n"
    report_content += "cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |\n"
    report_content += "cls.seq_relationship.bias                  | UNEXPECTED |  |\n"
    report_content += "cls.seq_relationship.weight                | UNEXPECTED |  |\n"
    report_content += "cls.predictions.bias                       | UNEXPECTED |  |\n\n"
    report_content += "Notes:\n"
    report_content += "- UNEXPECTED:   can be ignored when loading from different task/architecture; not ok if you expect identical arch.\n"
    report_content += "Epoch 1/10 | Loss: 0.3554 | F1: 0.9694\n"
    report_content += "Epoch 2/10 | Loss: 0.1244 | F1: 0.9831\n"
    report_content += "Epoch 3/10 | Loss: 0.0844 | F1: 0.9874\n"
    report_content += "Epoch 4/10 | Loss: 0.0805 | F1: 0.9873\n"
    report_content += "Epoch 5/10 | Loss: 0.0643 | F1: 0.9841\n"
    report_content += "Epoch 6/10 | Loss: 0.0521 | F1: 0.9894\n"
    report_content += "Epoch 7/10 | Loss: 0.0481 | F1: 0.9851\n"
    report_content += "Epoch 8/10 | Loss: 0.0422 | F1: 0.9895\n"
    report_content += "Epoch 9/10 | Loss: 0.0368 | F1: 0.9916\n"
    report_content += "Epoch 10/10 | Loss: 0.0322 | F1: 0.9873\n\n"
    report_content += "最终结果：\n"
    report_content += "准确率：0.9913\n"
    report_content += "精确率：0.9979\n"
    report_content += "召回率：0.9853\n"
    report_content += "F1分数：0.9916\n"
    report_content += "AUC分数：0.9993\n"
    report_content += "混淆矩阵：\n"
    report_content += "[[442   1]\n"
    report_content += " [  7 470]]\n"
    report_content += "误报率：0.0023\n"
    report_content += "漏报率：0.0147\n"
    report_content += "推理速度：843.80 样本/秒\n"
    report_content += "内存占用：0.01 MB\n\n"
    report_content += "===== 训练多模态模型 =====\n"
    report_content += "数据集统计：总样本4596, 钓鱼2298, 正常2298\n"
    report_content += "URL特征维度: 16\n"
    report_content += "网络行为特征维度: 8\n"
    report_content += "数据集统计：总样本4596, 钓鱼2298, 正常2298\n"
    report_content += "测试集URL特征维度: 16\n"
    report_content += "测试集网络行为特征维度: 8\n"
    report_content += "Loading weights: 100%|█████████████████████| 199/199 [00:00<00:00, 17026.37it/s]\n"
    report_content += "BertModel LOAD REPORT from: bert-base-chinese\n"
    report_content += "Key                                        | Status     |  |\n"
    report_content += "-------------------------------------------+------------+--+-\n"
    report_content += "cls.predictions.transform.dense.weight     | UNEXPECTED |  |\n"
    report_content += "cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |\n"
    report_content += "cls.predictions.transform.dense.bias       | UNEXPECTED |  |\n"
    report_content += "cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |\n"
    report_content += "cls.seq_relationship.bias                  | UNEXPECTED |  |\n"
    report_content += "cls.seq_relationship.weight                | UNEXPECTED |  |\n"
    report_content += "cls.predictions.bias                       | UNEXPECTED |  |\n\n"
    report_content += "Notes:\n"
    report_content += "- UNEXPECTED:   can be ignored when loading from different task/architecture; not ok if you expect identical arch.\n"
    report_content += "Epoch 1/20 | Loss: 0.6257 | Acc: 0.9641 | F1: 0.9664 | Saved best model to models/multimodal_best.pth\n"
    report_content += "Epoch 2/20 | Loss: 0.4919 | Acc: 0.9663 | F1: 0.9685 | Saved best model to models/multimodal_best.pth\n"
    report_content += "Epoch 3/20 | Loss: 0.3877 | Acc: 0.9674 | F1: 0.9695 | Saved best model to models/multimodal_best.pth\n"
    report_content += "Epoch 4/20 | Loss: 0.3079 | Acc: 0.9663 | F1: 0.9683 | Early stop counter: 1\n"
    report_content += "Epoch 5/20 | Loss: 0.2468 | Acc: 0.9815 | F1: 0.9823 | Saved best model to models/multimodal_best.pth\n"
    report_content += "Epoch 6/20 | Loss: 0.2048 | Acc: 0.9859 | F1: 0.9862 | Saved best model to models/multimodal_best.pth\n"
    report_content += "Epoch 7/20 | Loss: 0.1669 | Acc: 0.9815 | F1: 0.9819 | Early stop counter: 1\n"
    report_content += "Epoch 8/20 | Loss: 0.1375 | Acc: 0.9826 | F1: 0.9830 | Early stop counter: 2\n"
    report_content += "Epoch 9/20 | Loss: 0.1209 | Acc: 0.9826 | F1: 0.9829 | Early stop counter: 3\n"
    report_content += "Epoch 10/20 | Loss: 0.1147 | Acc: 0.9902 | F1: 0.9905 | Saved best model to models/multimodal_best.pth\n"
    report_content += "Epoch 11/20 | Loss: 0.1050 | Acc: 0.9870 | F1: 0.9873 | Early stop counter: 1\n"
    report_content += "Epoch 12/20 | Loss: 0.1012 | Acc: 0.9815 | F1: 0.9819 | Early stop counter: 2\n"
    report_content += "Epoch 13/20 | Loss: 0.0914 | Acc: 0.9826 | F1: 0.9830 | Early stop counter: 3\n"
    report_content += "Epoch 14/20 | Loss: 0.0920 | Acc: 0.9859 | F1: 0.9862 | Early stop counter: 4\n"
    report_content += "Epoch 15/20 | Loss: 0.0933 | Acc: 0.9859 | F1: 0.9862 | Early stop counter: 5\n"
    report_content += "Early stopping at epoch 15\n\n"
    report_content += "最终结果（测试集）：\n"
    report_content += "准确率：0.9906\n"
    report_content += "精确率：0.9939\n"
    report_content += "召回率：0.9874\n"
    report_content += "F1分数：0.9906\n"
    report_content += "AUC分数：0.9996\n"
    report_content += "混淆矩阵：\n"
    report_content += "[[2284   14]\n"
    report_content += " [  29 2269]]\n"
    report_content += "误报率：0.0061\n"
    report_content += "漏报率：0.0126\n"
    report_content += "</div>"
    report_content += "</div>"
    report_content += real_test_result
    report_content += "</div>"
    report_content += "</body>"
    report_content += "</html>"
    
    # 写入报告文件
    with open("./project_report.html", "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print("报告生成完成！文件保存为：project_report.html")
    print("\n报告特点：")
    print("1. 使用相对路径引用图片，方便移动到其他地方展示")
    print("2. 包含最新的真实世界测试结果")
    print("3. 自动检查图片文件是否存在，避免显示错误")
    print("4. 包含最新的数据集规模信息")

if __name__ == "__main__":
    generate_report()
